services:
  build:
    image: ${BUILD_IMAGE:-ghcr.io/sachnun/aqw-pocket:build-android}
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - KEYSTORE_PATH
      - KEYSTORE_FILE
      - KEY_ALIAS
      - KEYSTORE_ALIAS
      - KEYSTORE_PASS
      - KEYSTORE_PASSWORD
      - KEY_PASS
      - KEY_PASSWORD
